
-- indexes on the foreign keys

DROP INDEX IDX_SUPPLIER_NATION_KEY;

DROP INDEX IDX_PARTSUPP_PARTKEY;
DROP INDEX IDX_PARTSUPP_SUPPKEY;

DROP INDEX IDX_CUSTOMER_NATIONKEY;

DROP INDEX IDX_ORDERS_CUSTKEY;

DROP INDEX IDX_LINEITEM_ORDERKEY;
DROP INDEX IDX_LINEITEM_PART_SUPP;

DROP INDEX IDX_NATION_REGIONKEY;


-- aditional indexes

DROP INDEX IDX_LINEITEM_SHIPDATE;

DROP INDEX IDX_ORDERS_ORDERDATE;
